import { useState, useEffect } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Globe, ArrowLeft, ArrowRight } from "lucide-react";
import { LandingFooter } from "@/components/LandingFooter";

const texts = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last Updated",
    backHome: "Back to Home",
    sections: [
      {
        title: "1. Acceptance of Terms",
        content: "By accessing or using INFERA VisionFeasibility, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our platform. These terms constitute a legally binding agreement between you and INFERA VisionFeasibility."
      },
      {
        title: "2. Description of Service",
        content: "INFERA VisionFeasibility provides an AI-powered platform for generating investment feasibility studies. Our services include financial analysis (CAPEX, OPEX, Cash Flow, IRR, NPV, ROI), market analysis (TAM, SAM, SOM), risk assessment, and AI-generated recommendations in English and Arabic."
      },
      {
        title: "3. User Accounts",
        content: "You must register for an account to use our services. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You must provide accurate and complete registration information and keep it updated."
      },
      {
        title: "4. Subscription and Payment",
        content: "Paid subscriptions are billed according to the plan selected. Payments are processed securely via Stripe. Subscriptions auto-renew unless cancelled. Refunds are provided in accordance with our refund policy. Price changes will be notified 30 days in advance."
      },
      {
        title: "5. Acceptable Use",
        content: "You agree not to: use the service for illegal purposes, attempt to gain unauthorized access to our systems, interfere with other users' access, upload malicious content, or use automated systems to access the service without permission. Violation may result in account termination."
      },
      {
        title: "6. Intellectual Property",
        content: "INFERA VisionFeasibility owns all rights to the platform, AI models, and generated content formats. You retain ownership of your input data. Generated feasibility studies are licensed for your business use. You may not redistribute our AI technology or platform features."
      },
      {
        title: "7. AI-Generated Content",
        content: "Feasibility studies are generated by AI and are provided as analytical tools, not professional financial advice. We do not guarantee the accuracy of AI-generated content. Users should verify critical information and consult qualified professionals before making investment decisions."
      },
      {
        title: "8. Limitation of Liability",
        content: "INFERA VisionFeasibility is provided 'as is' without warranties. We are not liable for indirect, incidental, or consequential damages. Our total liability is limited to the amount paid for services in the 12 months preceding the claim."
      },
      {
        title: "9. Termination",
        content: "We may suspend or terminate accounts for Terms violations. You may cancel your subscription at any time. Upon termination, your access ends and data may be deleted after the retention period. Provisions regarding intellectual property and limitations survive termination."
      },
      {
        title: "10. Governing Law",
        content: "These Terms are governed by the laws of the jurisdiction where INFERA VisionFeasibility operates. Disputes will be resolved through binding arbitration. Class action lawsuits are waived by all parties."
      }
    ]
  },
  ar: {
    title: "شروط الخدمة",
    lastUpdated: "آخر تحديث",
    backHome: "العودة للرئيسية",
    sections: [
      {
        title: "1. قبول الشروط",
        content: "بالوصول إلى INFERA VisionFeasibility أو استخدامها، فإنك توافق على الالتزام بشروط الخدمة هذه. إذا كنت لا توافق على هذه الشروط، لا تستخدم منصتنا. تشكل هذه الشروط اتفاقية ملزمة قانونيًا بينك وبين INFERA VisionFeasibility."
      },
      {
        title: "2. وصف الخدمة",
        content: "توفر INFERA VisionFeasibility منصة مدعومة بالذكاء الاصطناعي لإنشاء دراسات الجدوى الاستثمارية. تشمل خدماتنا التحليل المالي (CAPEX، OPEX، التدفق النقدي، IRR، NPV، ROI)، تحليل السوق (TAM، SAM، SOM)، تقييم المخاطر، والتوصيات المولدة بالذكاء الاصطناعي باللغتين الإنجليزية والعربية."
      },
      {
        title: "3. حسابات المستخدمين",
        content: "يجب عليك التسجيل للحصول على حساب لاستخدام خدماتنا. أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك وعن جميع الأنشطة تحت حسابك. يجب عليك تقديم معلومات تسجيل دقيقة وكاملة والحفاظ على تحديثها."
      },
      {
        title: "4. الاشتراك والدفع",
        content: "تُفوتر الاشتراكات المدفوعة وفقًا للخطة المختارة. تتم معالجة المدفوعات بأمان عبر Stripe. تتجدد الاشتراكات تلقائيًا ما لم يتم إلغاؤها. يتم تقديم المبالغ المستردة وفقًا لسياسة الاسترداد الخاصة بنا. سيتم إخطارك بتغييرات الأسعار قبل 30 يومًا."
      },
      {
        title: "5. الاستخدام المقبول",
        content: "توافق على عدم: استخدام الخدمة لأغراض غير قانونية، محاولة الوصول غير المصرح به إلى أنظمتنا، التدخل في وصول المستخدمين الآخرين، تحميل محتوى ضار، أو استخدام أنظمة آلية للوصول إلى الخدمة دون إذن. قد يؤدي الانتهاك إلى إنهاء الحساب."
      },
      {
        title: "6. الملكية الفكرية",
        content: "تمتلك INFERA VisionFeasibility جميع الحقوق في المنصة ونماذج الذكاء الاصطناعي وتنسيقات المحتوى المولد. تحتفظ بملكية بيانات إدخالك. دراسات الجدوى المولدة مرخصة لاستخدامك التجاري. لا يجوز لك إعادة توزيع تقنية الذكاء الاصطناعي أو ميزات المنصة."
      },
      {
        title: "7. المحتوى المولد بالذكاء الاصطناعي",
        content: "يتم إنشاء دراسات الجدوى بواسطة الذكاء الاصطناعي وتُقدم كأدوات تحليلية وليس كمشورة مالية مهنية. لا نضمن دقة المحتوى المولد بالذكاء الاصطناعي. يجب على المستخدمين التحقق من المعلومات الحرجة واستشارة المتخصصين المؤهلين قبل اتخاذ قرارات الاستثمار."
      },
      {
        title: "8. تحديد المسؤولية",
        content: "يتم توفير INFERA VisionFeasibility 'كما هي' بدون ضمانات. لسنا مسؤولين عن الأضرار غير المباشرة أو العرضية أو التبعية. إجمالي مسؤوليتنا محدود بالمبلغ المدفوع مقابل الخدمات في الأشهر الـ 12 السابقة للمطالبة."
      },
      {
        title: "9. الإنهاء",
        content: "قد نعلق أو ننهي الحسابات بسبب انتهاكات الشروط. يمكنك إلغاء اشتراكك في أي وقت. عند الإنهاء، ينتهي وصولك وقد تُحذف البيانات بعد فترة الاحتفاظ. تبقى الأحكام المتعلقة بالملكية الفكرية والقيود سارية بعد الإنهاء."
      },
      {
        title: "10. القانون الحاكم",
        content: "تخضع هذه الشروط لقوانين الولاية القضائية التي تعمل فيها INFERA VisionFeasibility. سيتم حل النزاعات من خلال التحكيم الملزم. يتنازل جميع الأطراف عن الدعاوى الجماعية."
      }
    ]
  }
};

export default function Terms() {
  const [lang, setLang] = useState<"en" | "ar">(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("lang") as "en" | "ar") || "en";
    }
    return "en";
  });
  const isRtl = lang === "ar";
  const t = texts[lang];

  const toggleLanguage = () => {
    const newLang = lang === "en" ? "ar" : "en";
    setLang(newLang);
    localStorage.setItem("lang", newLang);
    document.documentElement.dir = newLang === "ar" ? "rtl" : "ltr";
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  return (
    <div className={`min-h-screen w-full bg-background ${isRtl ? 'text-right' : 'text-left'}`} dir={isRtl ? "rtl" : "ltr"}>
      <nav className="sticky top-0 z-50 w-full border-b bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between gap-4">
          <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer">
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-primary to-accent flex items-center justify-center">
                <span className="font-bold text-primary-foreground text-xs">IV</span>
              </div>
              <span className="font-bold text-lg">
                INFERA<span className="text-primary">Vision</span>
              </span>
            </div>
          </Link>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" onClick={toggleLanguage} data-testid="button-language">
              <Globe className="w-4 h-4" />
            </Button>
            <Link href="/">
              <Button variant="ghost" className="gap-2" data-testid="link-back-home">
                {isRtl ? <ArrowRight className="w-4 h-4" /> : <ArrowLeft className="w-4 h-4" />}
                {t.backHome}
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <main className="container mx-auto px-4 py-12 md:py-16">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold mb-4">{t.title}</h1>
          <p className="text-muted-foreground mb-8">
            {t.lastUpdated}: January 2026
          </p>

          <div className="space-y-8">
            {t.sections.map((section, index) => (
              <section key={index}>
                <h2 className="text-xl font-semibold mb-3">{section.title}</h2>
                <p className="text-muted-foreground leading-relaxed">{section.content}</p>
              </section>
            ))}
          </div>
        </div>
      </main>

      <LandingFooter lang={lang} />
    </div>
  );
}
